endpoint:
  - wss://rpc.polkadot.io
  - wss://polkadot-rpc.dwellir.com
  - wss://polkadot-rpc-tn.dwellir.com
  - wss://rpc-polkadot.luckyfriday.io
mock-signature-host: true
block: ${env.POLKADOT_BLOCK_NUMBER}
db: ./db.sqlite
# wasm-override: polkadot_runtime.compact.compressed.wasm

import-storage:
  System:
    Account:
      -
        -
          - 5GrwvaEF5zXb26Fz9rcQpDWS57CtERHpNehXCPcNoHGKutQY
        - providers: 1
          data:
            free: '10000000000000000000'
  ParasDisputes:
    $removePrefix: ['disputes'] # those can makes block building super slow
