endpoint:
  - wss://asset-hub-polkadot-rpc.dwellir.com
  - wss://rpc-asset-hub-polkadot.luckyfriday.io
  - wss://statemint-rpc-tn.dwellir.com
  - wss://polkadot-asset-hub-rpc.polkadot.io
mock-signature-host: true

import-storage:
  System:
    Account:
      -
        -
          - 5GrwvaEF5zXb26Fz9rcQpDWS57CtERHpNehXCPcNoHGKutQY # # Alice, dot
        - providers: 1
          data:
            free: 1000000000000000
  Assets:
    Account:
      -
        -
          - 1337 # Alice, USDC
          - 5GrwvaEF5zXb26Fz9rcQpDWS57CtERHpNehXCPcNoHGKutQY
        - balance: 10000000000
      -
        -
          - 1984 # Alice, usdt
          - 5GrwvaEF5zXb26Fz9rcQpDWS57CtERHpNehXCPcNoHGKutQY
        - balance: 10000000000
      -
        -
          - 1337 # Sibling:2032 (Interlay), USDC
          - 13cKp89UHns9eDQQV3CZ1seFH6QQ6bnVeLHe4SpsekeJse1r
        - balance: 100000000000
      -
        -
          - 1984 # Sibling:2032 (Interlay), usdt
          - 13cKp89UHns9eDQQV3CZ1seFH6QQ6bnVeLHe4SpsekeJse1r
        - balance: 100000000000