endpoint:
  - wss://statemine-rpc.dwellir.com
  - wss://rpc-asset-hub-kusama.luckyfriday.io
  - wss://statemine-rpc-tn.dwellir.com
  - wss://kusama-asset-hub-rpc.polkadot.io
mock-signature-host: true
block: ${env.STATEMINE_BLOCK_NUMBER}

import-storage:
  System:
    Account:
      -
        -
          - 5GrwvaEF5zXb26Fz9rcQpDWS57CtERHpNehXCPcNoHGKutQY
        - providers: 1
          data:
            free: 1000000000000000
  Assets:
    Account:
      -
        -
          - 1984 # Alice, usdt
          - 5GrwvaEF5zXb26Fz9rcQpDWS57CtERHpNehXCPcNoHGKutQY
        - balance: 10000000000
