name: npm

on:
    push:
        tags:
            - "*"

jobs:
    publish:
        runs-on: [self-hosted, linux]
        steps:
            - uses: actions/checkout@v3
            - name: Read .nvmrc
              run: echo "##[set-output name=NVMRC;]$(cat .nvmrc)"
              id: nvm
            - name: Use Node.js (.nvmrc)
              uses: actions/setup-node@v1
              with:
                node-version: "${{ steps.nvm.outputs.NVMRC }}"
            - run: corepack enable
            - run: yarn install
            - run: yarn build
            - run: echo "RELEASE_VERSION=${GITHUB_REF:10}" >> $GITHUB_ENV
            - run: echo ${RELEASE_VERSION}
            - name: publish
              run: |
                  git config --global user.email "${GITHUB_ACTOR}"
                  git config --global user.name "${GITHUB_ACTOR}"
                  yarn publish --access public --new-version ${RELEASE_VERSION}
              env:
                  NODE_AUTH_TOKEN: ${{ secrets.NODE_AUTH_TOKEN }}
