  
name: PR
on: [pull_request]

jobs:
  pr:
    strategy:
      matrix:
        step: ['lint', 'build', 'test:ci']
    name: ${{ matrix.step }}
    runs-on: ubuntu-latest
    steps:
    - uses: actions/checkout@v2
    - uses: actions/setup-node@v3
      with:
          node-version-file: ".nvmrc"
          registry-url: "https://registry.npmjs.org"
          always-auth: true
    - name: ${{ matrix.step }}
      run: |
        yarn install
        yarn ${{ matrix.step }}

