name: Master
on:
  push:
    branches:
      - master

jobs:
  master:
    name: build
    runs-on: [self-hosted, linux]
    permissions:
      contents: read
      packages: write
    steps:
      - uses: actions/checkout@v3
      - name: Read .nvmrc
        run: echo "##[set-output name=NVMRC;]$(cat .nvmrc)"
        id: nvm
      - name: Use Node.js (.nvmrc)
        uses: actions/setup-node@v1
        with:
          node-version: "${{ steps.nvm.outputs.NVMRC }}"
      - name: yarn
        run: |
          yarn install --immutable
          yarn build
      - name: publish
        run: |
          npm publish
        env:
          NODE_AUTH_TOKEN: ${{ secrets.GITHUB_TOKEN }}
