name: Master
on:
  push:
    branches:
      - master

jobs:
  master:
    name: build
    runs-on: [self-hosted, linux]
    permissions:
      contents: read
      packages: write
    steps:
      - uses: actions/checkout@v3
      - uses: actions/setup-node@v4
        with:
          node-version-file: ".nvmrc"
      - name: yarn
        run: |
          yarn install --immutable
          yarn build
