name: Master
on:
  push:
    branches:
      - master

jobs:
  master:
    strategy:
      matrix:
        step: ["build:release"]
    name: ${{ matrix.step }}
    if: "! startsWith(github.event.head_commit.message, '[CI Skip]')"
    runs-on: [self-hosted, linux]
    steps:
      - uses: actions/checkout@v3
      - name: ${{ matrix.step }}
        run: |
          yarn install --immutable | grep -v 'YN0013'
          yarn ${{ matrix.step }}

