name: Master
on:
  push:
    branches:
      - master

jobs:
  master:
    name: build
    runs-on: [self-hosted, linux]
    steps:
      - uses: actions/checkout@v3
      - name: yarn
        run: |
          yarn install --immutable
          yarn build
