---
name: Daily XCM tests
on:
  schedule:
    - cron: '5 * * * *' # Run hourly
  push:
    branches:
      - master
  pull_request:
    branches:
      - master


jobs:
  chopsticks_kintsugi_test:
    runs-on: [self-hosted, linux]
    timeout-minutes: 30
    container:
      image: ghcr.io/interlay/chopsticks:master
    steps:
      - name: Checkout
        uses: actions/checkout@v3

      - name: Run Kintsugi tests
        uses: nick-fields/retry@v2
        with:
          max_attempts: 3
          retry_on: error
          timeout_minutes: 10
          on_retry_command: pkill node; sleep 2
          command: |
            echo "Launching chopsticks..."
            cd /app
            echo "Start..." > log.txt
            yarn start xcm \
              --relaychain=configs/kusama.yml \
              --parachain=configs/kintsugi.yml \
              --parachain=configs/statemine.yml \
              --parachain=configs/karura.yml \
              --parachain=configs/parallel-heiko.yml \
              --parachain=configs/bifrost.yml \
              &> log.txt &
            echo "Waiting for log to show chopsticks is ready..."
            tail -f log.txt | grep -q "Connected parachains"
            echo "Chopsticks launched, start tests."
            cd -

            yarn install --frozen-lockfile
            npx ts-node scripts/kintsugi-chopsticks-test.ts

      - name: Report status to Discord
        uses: sarisia/actions-status-discord@v1
        if: failure()
        with:
          webhook: ${{ secrets.DISCORD_WEBHOOK }}
      - name: Upload logs
        if: failure()
        uses: actions/upload-artifact@v3
        with:
          name: kintsugi-chopsticks-logs
          path: /app/log.txt
          retention-days: 14

  chopsticks_interlay_test:
    runs-on: [self-hosted, linux]
    timeout-minutes: 30
    container:
      image: ghcr.io/interlay/chopsticks:master
    steps:
      - name: Checkout
        uses: actions/checkout@v3

      - name: Run Interlay tests
        uses: nick-fields/retry@v2
        with:
          max_attempts: 3
          retry_on: error
          timeout_minutes: 10
          on_retry_command: pkill node; sleep 2
          command: |
            echo "Launching chopsticks..."
            cd /app
            echo "Start..." > log.txt
            yarn start xcm \
              --relaychain=configs/polkadot.yml \
              --parachain=configs/interlay.yml \
              --parachain=configs/statemint.yml \
              --parachain=configs/hydradx.yml \
              --parachain=configs/acala.yml \
              --parachain=configs/astar.yml \
              --parachain=configs/parallel.yml \
              &> log.txt &
            echo "Waiting for log to show chopsticks is ready..."
            tail -f log.txt | grep -q "Connected parachains"
            echo "Chopsticks launched, start tests."
            cd -

            yarn install --frozen-lockfile
            npx ts-node scripts/interlay-chopsticks-test.ts

      - name: Report status to Discord
        uses: sarisia/actions-status-discord@v1
        if: failure()
        with:
          webhook: ${{ secrets.DISCORD_WEBHOOK }}
      - name: Upload logs
        if: failure()
        uses: actions/upload-artifact@v3
        with:
          name: interlay-chopsticks-logs
          path: /app/log.txt
          retention-days: 14
