---
name: AssetHub XCM tests
on:
  schedule:
    - cron: '38 */2 * * *' # Run every 2 hours
  push:
    branches:
      - master
  pull_request:
    branches:
      - master

jobs:
  chopsticks_kusama_assethub_test:
    runs-on: ubuntu-latest
    timeout-minutes: 10
    steps:
      - name: Checkout
        uses: actions/checkout@v4

      - name: Launch chopsticks
        timeout-minutes: 3
        run: |
          npx --yes @acala-network/chopsticks@0.9.10 \
            xcm \
            -r scripts/configs/kusama.yml \
            -p scripts/configs/kintsugi.yml \
            -p scripts/configs/statemine.yml \
            &> log.txt &
          echo "Waiting for log to show chopsticks is ready..."
          tail -f log.txt | grep -q "Connected parachains"
          echo "... detected chopsticks is ready."

      - name: Run Kusama AssetHub tests
        run: |
          yarn install --frozen-lockfile
          npx ts-node scripts/kusama-chopsticks-assethub-test.ts
      - name: Show error log
        if: failure()
        run: |
          tail -n 100 log.txt
      - name: Report status to Discord
        uses: sarisia/actions-status-discord@v1
        if: failure()
        with:
          webhook: ${{ secrets.DISCORD_WEBHOOK }}

  chopsticks_polkadot_assethub_test:
    runs-on: ubuntu-latest
    timeout-minutes: 10
    steps:
      - name: Checkout
        uses: actions/checkout@v4

      - name: Launch chopsticks
        timeout-minutes: 3
        run: |
          npx --yes @acala-network/chopsticks@0.9.10 \
            xcm \
            -r scripts/configs/polkadot.yml \
            -p scripts/configs/interlay.yml \
            -p scripts/configs/statemint.yml \
            &> log.txt &
          echo "Waiting for log to show chopsticks is ready..."
          tail -f log.txt | grep -q "Connected parachains"
          echo "... detected chopsticks is ready."

      - name: Run Polkadot AssetHub tests
        run: |
          yarn install --frozen-lockfile
          npx ts-node scripts/polkadot-chopsticks-assethub-test.ts
      - name: Show error log
        if: failure()
        run: |
          tail -n 100 log.txt
      - name: Report status to Discord
        uses: sarisia/actions-status-discord@v1
        if: failure()
        with:
          webhook: ${{ secrets.DISCORD_WEBHOOK }}
